name = "iran-flight-trackrt-dashboard"
main = "worker.js"
compatibility_date = "2026-07-01"

[triggers]
crons = ["0 0 * * *"]

[[kv_namespaces]]
binding = "FLIGHTS_KV"
id = "2b0a55517b5a466dbb6b896275f02494"
